import type { CopyKey } from "./i18n";

/** Admin console only. The public site stays English, Czech, or Urdu. */
export const ADMIN_UK: Partial<Record<CopyKey, string>> = {
  loading: "Завантаження",
  save: "Зберегти",
  remove: "Прибрати",
  edit: "Змінити",
  add: "Додати",
  active: "Активна",
  all: "Усі",
  seat: "Вакансія",
  quota: "Вільні місця",
  title: "Назва",
  position: "Посада",
  photo: "Фото",
  phone: "Телефон",
  name: "Ім’я",
  description: "Опис",
  housing: "Житло",
  hours: "Графік",
  salary: "Оплата",
  employer: "Роботодавець",
  blocked: "Громадянства, яким не можна подаватися",
  field_requirements: "Що потрібно від кандидата",
  messages: "Нотатки у справі",
  message_send: "Надіслати",
  filings_id: "Справа",
  filings_date: "Подано",
  portal_paid: "Сплачено",
  portal_next_closed: "Цю справу закрито.",
  status_cancelled: "Скасовано",
  ps_IN_PROCESS: "В обробці",
  ps_EMPLOYER_SUBMITTED: "Подано роботодавцю",
  ps_EMPLOYER_APPROVED_FOR_MINISTRY: "Роботодавець погодив подання до міністерства",
  ps_LEGAL_SERVICE: "Юридична підготовка",
  ps_MINISTRY_SUBMITTED: "Подано до міністерства",
  ps_MINISTRY_REVIEW: "На розгляді в міністерстві",
  ps_MINISTRY_APPROVED: "Міністерство погодило",
  ps_FINAL_LEGAL_SERVICE: "Фінальне юридичне оформлення",
  admin_kicker: "Консоль практики",
  admin_live_note: "Те, що збережено тут, бачить кожен відвідувач. Змінити може лише адміністратор.",
  admin_denied: "Ця консоль для практики, не для клієнтського акаунта.",
  admin_overview: "Огляд",
  admin_apps: "Заявки",
  admin_vacancies: "Вакансії",
  admin_team: "Команда",
  admin_content: "Зміст",
  admin_pricing: "Ціни",
  admin_audit: "Журнал",
  admin_clients: "нові анкети",
  admin_review: "квитанції на перевірку",
  admin_live: "відкриті справи",
  admin_accept: "Прийняти справу",
  admin_reject: "Відхилити",
  admin_to3: "Підтвердити оплату · етап 3",
  admin_need_proof: "У справі немає квитанції на перші 30%. Додайте її, потім підтвердіть ще раз.",
  admin_proof_ready: "Квитанція вже в справі. Натисніть «Підтвердити оплату», щоб перейти на етап 3.",
  admin_proof_add: "Додати квитанцію 30%",
  admin_stage_ok: "Етап змінено.",
  admin_not_ready: "Цю справу зараз не можна перевести.",
  admin_need_final: "Спочатку завантажте фінальний документ.",
  admin_busy: "Таблиця зайнята. Зачекайте хвилину і натисніть ще раз.",
  admin_to4: "Відкрити фінальну оплату",
  admin_reason: "Причина, якщо відхиляєте",
  admin_process: "Етап документів",
  admin_final_upload: "Завантажити фінальні документи клієнта",
  admin_dispatch: "Трек кур’єра або логін порталу, який віддасте",
  admin_new_app: "Відкрити справу для клієнта",
  admin_email: "Пошта клієнта",
  admin_create: "Створити справу",
  admin_users: "Акаунти",
  admin_delete_user: "Видалити",
  admin_delete_user_ask: "Видалити цей акаунт? Увійти він більше не зможе. Справи залишаться.",
  admin_delete_self: "Не можна видалити акаунт, з якого ви зараз увійшли.",
  admin_last_admin: "Останній акаунт адміністратора видалити не можна.",
  admin_story: "Про нас, ця мова сайту",
  admin_license: "Зображення ліцензії",
  admin_office: "Фото офісу",
  admin_field_phone: "Телефон",
  admin_field_email: "Пошта",
  admin_field_address: "Адреса",
  admin_field_wallet: "Криптогаманець",
  admin_field_network: "Мережа гаманця",
  admin_field_entity: "Юридична назва",
  admin_field_id: "Номер компанії",
  admin_field_vat: "ПДВ",
  admin_field_court: "Судовий запис",
  admin_field_regulator: "Ліцензійний орган",
  admin_field_tg_owner: "Сповіщення власнику",
  admin_field_tg_staff: "Сповіщення команді",
  admin_field_rate: "Ставка субагента, відсоток",
  admin_replace_photo: "Замінити фото",
  admin_photo_ready: "Нове фото готове. Збережіть, щоб опублікувати.",
  admin_file_big: "Візьміть менше зображення.",
  admin_saved: "Збережено. Сайт уже показує цю зміну.",
  admin_unsaved: "Не збережено. Напишіть, що саме написала помилка, і спробуйте ще раз.",
  admin_drive: "Google Drive не прийняв фото. Папка сховища має бути відкрита для облікового запису практики як редактор.",
  admin_photo_wait: "Завантажую фото…",
  admin_photo_heic: "Цей файл не вдалося відкрити як фото. Підійде JPEG, PNG, WEBP, GIF, HEIC з айфона.",
  admin_photo_ok: "Фото збережено.",
  admin_partner: "Назва роботодавця",
  admin_show_all: "Показати незавершені",
  admin_search: "Пошук за ім’ям або поштою",
  admin_overdue: "Лише прострочені",
  admin_unassigned: "Без менеджера",
  admin_stage: "Етап",
  admin_country: "Країна",
  admin_assign: "Призначити",
  admin_action: "Дія",
  admin_pick_hint: "Галочка лише призначає менеджера. Справу приймає кнопка в цьому рядку.",
  admin_export: "Записати відкриті справи",
  admin_exported: "Справи записано",
  admin_doc_ok: "Прийняти",
  admin_doc_no: "Відхилити",
  close: "Закрити",
  download: "Завантажити",
  admin_open: "Відкрити",
  admin_back: "Усі справи",
  admin_vault: "Google Drive практики",
  admin_vault_help: "Щоб фото, досьє і PDF зберігались у вашу папку, підключіть Gmail власника папки. У Google Cloud для цього клієнта Redirect URI має бути рівно адреса нижче. На екрані згоди додайте цей Gmail як тестового користувача. Якщо поля Client ID і Secret видно — вставте їх і натисніть кнопку. Дозволяйте доступ саме тим акаунтом, який володіє папкою.",
  admin_vault_help_ready: "Клієнт Google уже на сервері. Натисніть кнопку і дозвольте доступ Gmail, якому належить папка на Диску.",
  admin_vault_on: "Ваш Google підключено. Нові файли зберігатимуться у вашій папці.",
  admin_vault_off: "Ваш Google ще не підключено. Поки що в папку нічого не запишеться.",
  admin_vault_go: "Підключити мій Google",
  admin_vault_again: "Підключити знову",
  admin_vault_uri: "Redirect URI",
  admin_vault_ok: "Google підключено.",
  admin_vault_fail: "Не вдалося підключити. Перевірте Client ID, секрет і Redirect URI.",
  admin_file_miss: "Файл не відкривається. Спробуйте ще раз.",
  admin_files_empty: "Клієнт ще нічого не завантажив у цю справу.",
  cat_PASSPORT: "Паспорт",
  cat_POLICE_CLEARANCE: "Довідка про несудимість",
  cat_PHOTO: "Фото",
  cat_EDUCATION: "Освіта",
  cat_MEDICAL: "Медична",
  cat_OTHER: "Інше",
  cat_PAYMENT_PROOF: "Квитанція 30%",
  cat_FINAL: "Фінальні документи",
  admin_id_search: "Номер справи",
  admin_empty_cases: "На цій сторінці справ немає.",
  admin_block_q: "Чекаємо анкету.",
  admin_block_pay: "Чекаємо підтвердження перших 30%.",
  admin_block_doc: "Документ відхилено. Його можна замінити в цій справі.",
  admin_block_ok: "Ніщо не блокує наступний крок.",
  admin_waiting_doc: "Чекаємо документ",
  admin_only_mine: "Показано справи, призначені вам.",
  admin_history: "Що змінилося",
  admin_referrer: "Субагент",
  admin_referrer_none: "Немає",
  admin_offered: "Є в калькуляторі",
  admin_motion: "Анімувати чотири кроки",
  admin_count_filed: "Показувати, скільки справ подано",
  admin_count_issued: "Показувати, скільки дозволів видано",
  admin_banner: "Верхній банер",
  admin_banner_text: "Рядок банера, ця мова сайту",
  admin_banner_country: "Банер відкриває цю країну",
  admin_banner_start: "Банер від",
  admin_banner_end: "Банер до",
  admin_country_photo: "Фото країни",
  admin_vacancy_photo: "Фото робочого місця",
  admin_logo: "Логотип роботодавця",
  admin_cover: "Показувати першим",
  admin_hide: "Сховати",
  admin_show: "Показати знову",
  admin_caption: "Підпис",
  admin_three: "Трьох фото досить. Спочатку сховайте одне.",
  admin_steps: "Чотири кроки, ця мова сайту",
  admin_order: "Порядок",
  hang_money: "Оплата висить більше ніж 2 дні",
  hang_list: "Рахунки без підтвердження",
  reject_blur: "Суму не прочитати",
  reject_name: "Ім’я не збігається",
  reject_page: "Забагато сторінок",
  reject_other: "Інше",
  reject_line: "Одне речення",
  case_write: "Написати",
  price_kept: "Відкриті справи лишають гонорар, з яким їх відкрили.",
  price_who: "Хто і коли змінив ціну",
  hide_until: "Сховати до дати",
  account_restore: "Відкрити рахунок знову",
  copy_vac: "Скопіювати в іншу країну",
  hours_field: "Години офісу на сайті",
  review_need: "Відгук потребує імені, країни, дати і тексту. Неповний рядок не показується.",
  phone_same: "Той самий телефон, що в іншої відкритої справи",
  agent_comm: "Комісія",
  agent_pay_paid: "Виплачено",
  agent_pay_due: "До виплати",
  admin_user_cases: "Відкриті справи",
  admin_no_open: "Відкритих справ немає.",
};
