import type { CopyKey } from "./i18n";

/** Admin console only. The public site stays English, Czech, or Urdu. */
export const ADMIN_UK: Partial<Record<CopyKey, string>> = {
  loading: "Завантаження",
  save: "Зберегти",
  remove: "Прибрати",
  edit: "Змінити",
  add: "Додати",
  active: "Активна",
  all: "Усі",
  seat: "Вакансія",
  quota: "Вільні місця",
  title: "Назва",
  position: "Посада",
  photo: "Фото",
  phone: "Телефон",
  name: "Ім’я",
  description: "Опис",
  housing: "Житло",
  hours: "Графік",
  salary: "Оплата",
  employer: "Роботодавець",
  blocked: "Громадянства, яким не можна подаватися",
  field_requirements: "Що потрібно від кандидата",
  messages: "Нотатки у справі",
  message_send: "Надіслати",
  filings_id: "Справа",
  filings_date: "Подано",
  portal_paid: "Сплачено",
  portal_next_closed: "Цю справу закрито.",
  status_cancelled: "Скасовано",
  ps_IN_PROCESS: "В обробці",
  ps_EMPLOYER_SUBMITTED: "Подано роботодавцю",
  ps_EMPLOYER_APPROVED_FOR_MINISTRY: "Роботодавець погодив подання до міністерства",
  ps_LEGAL_SERVICE: "Юридична підготовка",
  ps_MINISTRY_SUBMITTED: "Подано до міністерства",
  ps_MINISTRY_REVIEW: "На розгляді в міністерстві",
  ps_MINISTRY_APPROVED: "Міністерство погодило",
  ps_FINAL_LEGAL_SERVICE: "Фінальне юридичне оформлення",
  admin_kicker: "Консоль практики",
  admin_live_note: "Те, що збережено тут, бачить кожен відвідувач. Змінити може лише адміністратор.",
  admin_denied: "Ця консоль для практики, не для клієнтського акаунта.",
  admin_overview: "Огляд",
  admin_apps: "Заявки",
  admin_vacancies: "Вакансії",
  admin_team: "Команда",
  admin_content: "Зміст",
  admin_pricing: "Ціни",
  admin_audit: "Журнал",
  admin_clients: "нові анкети",
  admin_review: "квитанції на перевірку",
  admin_live: "відкриті справи",
  admin_accept: "Прийняти справу",
  admin_reject: "Відхилити",
  admin_to3: "Підтвердити оплату · етап 3",
  admin_to4: "Відкрити фінальну оплату",
  admin_reason: "Причина, якщо відхиляєте",
  admin_process: "Етап документів",
  admin_final_upload: "Завантажити фінальні документи клієнта",
  admin_dispatch: "Трек кур’єра або логін порталу, який віддасте",
  admin_new_app: "Відкрити справу для клієнта",
  admin_email: "Пошта клієнта",
  admin_create: "Створити справу",
  admin_users: "Акаунти",
  admin_story: "Про нас, ця мова сайту",
  admin_license: "Зображення ліцензії",
  admin_office: "Фото офісу",
  admin_field_phone: "Телефон",
  admin_field_email: "Пошта",
  admin_field_address: "Адреса",
  admin_field_wallet: "Криптогаманець",
  admin_field_network: "Мережа гаманця",
  admin_field_entity: "Юридична назва",
  admin_field_id: "Номер компанії",
  admin_field_vat: "ПДВ",
  admin_field_court: "Судовий запис",
  admin_field_regulator: "Ліцензійний орган",
  admin_field_tg_owner: "Сповіщення власнику",
  admin_field_tg_staff: "Сповіщення команді",
  admin_field_rate: "Ставка субагента, відсоток",
  admin_replace_photo: "Замінити фото",
  admin_photo_ready: "Нове фото готове. Збережіть, щоб опублікувати.",
  admin_file_big: "Візьміть менше зображення.",
  admin_partner: "Назва роботодавця",
  admin_show_all: "Показати незавершені",
  admin_search: "Пошук за ім’ям або поштою",
  admin_overdue: "Лише прострочені",
  admin_unassigned: "Без менеджера",
  admin_stage: "Етап",
  admin_country: "Країна",
  admin_assign: "Призначити",
  admin_action: "Дія",
  admin_pick_hint: "Галочка лише призначає менеджера. Справу приймає кнопка в цьому рядку.",
  admin_export: "Записати відкриті справи",
  admin_exported: "Справи записано",
  admin_doc_ok: "Прийняти",
  admin_doc_no: "Відхилити",
  admin_open: "Відкрити",
  admin_id_search: "Номер справи",
  admin_empty_cases: "На цій сторінці справ немає.",
  admin_block_q: "Чекаємо анкету.",
  admin_block_pay: "Чекаємо підтвердження перших 30%.",
  admin_block_doc: "Документ відхилено. Його можна замінити в цій справі.",
  admin_block_ok: "Ніщо не блокує наступний крок.",
  admin_waiting_doc: "Чекаємо документ",
  admin_only_mine: "Показано справи, призначені вам.",
  admin_history: "Що змінилося",
  admin_referrer: "Субагент",
  admin_referrer_none: "Немає",
  admin_offered: "Є в калькуляторі",
  admin_motion: "Анімувати чотири кроки",
  admin_count_filed: "Показувати, скільки справ подано",
  admin_count_issued: "Показувати, скільки дозволів видано",
  admin_banner: "Верхній банер",
  admin_banner_text: "Рядок банера, ця мова сайту",
  admin_banner_country: "Банер відкриває цю країну",
  admin_banner_start: "Банер від",
  admin_banner_end: "Банер до",
  admin_country_photo: "Фото країни",
  admin_vacancy_photo: "Фото робочого місця",
  admin_logo: "Логотип роботодавця",
  admin_cover: "Показувати першим",
  admin_hide: "Сховати",
  admin_show: "Показати знову",
  admin_caption: "Підпис",
  admin_three: "Трьох фото досить. Спочатку сховайте одне.",
  admin_steps: "Чотири кроки, ця мова сайту",
  admin_order: "Порядок",
};
