import React,{useEffect,useMemo,useState} from 'react';
import { useAuth } from '../context/AuthContext';
import { adminApi,applicationsApi,documentsApi,dossiersApi,paymentsApi,teamApi,vacanciesApi } from '../services/api';
import type { Application,Dossier,DossierDocument,PaymentTransaction,PricingItem,Vacancy,TeamMember,User,AuditLogEntry } from '../types';
import { LayoutDashboard,Users,Briefcase,FileText,CreditCard,ClipboardList,Settings,ShieldCheck,Image,Database,History,LifeBuoy,Plus,Edit3,Archive,Check, X,RefreshCw,Save,Search,SlidersHorizontal } from 'lucide-react';

const sections=[['overview','Overview',LayoutDashboard],['applications','Applications',ClipboardList],['dossiers','Dossiers',FileText],['documents','Documents',FileText],['payments','Finance',CreditCard],['sla','SLA / Legal',ShieldCheck],['vacancies','Vacancies',Briefcase],['batch','Batch operations',SlidersHorizontal],['managers','Managers & users',Users],['team','Team / gallery',Image],['pricing','Pricing',Database],['content','Content / settings',Settings],['audit','Audit log',History],['backups','Backups',Database],['support','Support',LifeBuoy]] as const;
const label=(s:string)=>s.replace(/_/g,' ');
export const AdminPanel:React.FC=()=>{const {user}=useAuth();const [section,setSection]=useState<string>('overview');const [loading,setLoading]=useState(true);const [stats,setStats]=useState<any>({});const [apps,setApps]=useState<Application[]>([]);const [dossiers,setDossiers]=useState<Dossier[]>([]);const [docs,setDocs]=useState<DossierDocument[]>([]);const [payments,setPayments]=useState<PaymentTransaction[]>([]);const [vacancies,setVacancies]=useState<Vacancy[]>([]);const [users,setUsers]=useState<User[]>([]);const [team,setTeam]=useState<TeamMember[]>([]);const [audit,setAudit]=useState<AuditLogEntry[]>([]);const [pricing,setPricing]=useState<PricingItem[]>([]);const [search,setSearch]=useState('');const [editVac,setEditVac]=useState<Partial<Vacancy>|null>(null);const [newPricing,setNewPricing]=useState<Partial<PricingItem>>({currency:'EUR',active:true});const [setting,setSetting]=useState({key:'',value:''});const [gallery,setGallery]=useState({title:'',imageUrl:'',caption:'',order:'0'});const [teamForm,setTeamForm]=useState<Partial<TeamMember>|null>(null);
 const load=async()=>{setLoading(true);try{const [s,a,d,v,u,t,au,p,pa]=await Promise.all([adminApi.dashboard(),applicationsApi.list(),dossiersApi.list(),vacanciesApi.list(),adminApi.users(),teamApi.list(),adminApi.audit(),adminApi.pricing(),paymentsApi.list()]);setStats(s);setApps(a.applications);setDossiers(d.dossiers);setVacancies(v.vacancies);setUsers(u.users);setTeam(t.team);setAudit(au.logs);setPricing(p.items);setPayments(pa.payments);const docsAll:DossierDocument[]=[];for(const dossier of d.dossiers){try{const r=await documentsApi.list(dossier.id);docsAll.push(...r.documents)}catch{}}setDocs(docsAll);}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const filteredVac=useMemo(()=>vacancies.filter(v=>`${v.country} ${v.title} ${v.category}`.toLowerCase().includes(search.toLowerCase())),[vacancies,search]);
 const createFromApp=async(a:Application)=>{const v=vacancies.find(x=>x.id===a.vacancyId);if(!v)return alert('Vacancy not found.');const p=pricing.find(x=>x.active);if(!p)return alert('Create an active pricing item first.');let data:any={};try{data=JSON.parse(a.applicantData||'{}')}catch{}const d=await dossiersApi.create({fullName:data.fullName||'Client',passportNumber:data.passportNumber||'PENDING',citizenship:data.citizenship||'PENDING',targetCountry:v.country,vacancyId:v.id,vacancyTitle:v.title,pricingId:p.id,totalCost:p.amount,currency:p.currency});await applicationsApi.update({applicationId:a.id,status:'ACCEPTED'});alert(`Dossier ${d.dossier.id} created.`);await load()};
 const reviewDoc=async(id:string,status:'APPROVED'|'REJECTED')=>{await documentsApi.review({documentId:id,status,rejectionReason:status==='REJECTED'?'Returned for correction':''});await load()};
 const reviewPay=async(id:string,status:'CONFIRMED'|'REJECTED'|'REFUNDED')=>{await paymentsApi.review({paymentId:id,status});await load()};
 const saveVacancy=async()=>{if(!editVac?.title)return;if(editVac.id)await vacanciesApi.update(editVac);else await vacanciesApi.create(editVac);setEditVac(null);await load()};
 const saveTeam=async()=>{if(!teamForm?.fullName)return;if(teamForm.id)await teamApi.update({memberId:teamForm.id,...teamForm});else await teamApi.create(teamForm);setTeamForm(null);await load()};
 if(loading)return <div className="page-wrap"><div className="skeleton-card">Loading command center…</div></div>;
 return <div className="admin-shell"><aside className="admin-side"><div className="admin-brand"><div className="brand-mark">V</div><div><strong>VANGUARD</strong><small>EXECUTIVE CONSOLE</small></div></div><div className="admin-user">{user?.fullName}<span>{user?.roles.join(' · ')}</span></div><nav>{sections.map(([id,name,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon size={16}/><span>{name}</span></button>)}</nav></aside><main className="admin-main"><div className="admin-top"><div><p className="eyebrow">SECURE OPERATIONS</p><h1>{sections.find(x=>x[0]===section)?.[1]}</h1></div><button className="icon-btn" onClick={()=>void load()}><RefreshCw size={17}/></button></div>
 {section==='overview'&&<Overview stats={stats} apps={apps} docs={docs} payments={payments} dossiers={dossiers}/>} 
 {section==='applications'&&<ApplicationsView apps={apps} vacancies={vacancies} onUpdate={async(a,s)=>{await applicationsApi.update({applicationId:a.id,status:s});await load()}} onCreateDossier={createFromApp}/>} 
 {section==='dossiers'&&<DossiersView dossiers={dossiers} onUpdate={async(d,processStatus)=>{await dossiersApi.updateStatus({dossierId:d.id,processStatus});await load()}}/>}
 {section==='documents'&&<DocumentsView docs={docs} onReview={reviewDoc}/>} 
 {section==='payments'&&<PaymentsView payments={payments} onReview={reviewPay}/>} 
 {section==='sla'&&<SLAVView dossiers={dossiers} docs={docs} payments={payments}/>} 
 {section==='vacancies'&&<section className="panel"><div className="panel-head"><div><h2>Vacancy management</h2><p>Create, edit, activate, archive and filter vacancies by country.</p></div><button className="primary-btn" onClick={()=>setEditVac({isActive:true,quotaRemaining:0})}><Plus size={16}/> New vacancy</button></div><div className="toolbar"><div className="search"><Search size={15}/><input placeholder="Search country, title, category" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="table-wrap"><table><thead><tr><th>Country</th><th>Position</th><th>Salary</th><th>Quota</th><th>Status</th><th></th></tr></thead><tbody>{filteredVac.map(v=><tr key={v.id}><td>{v.country}</td><td><b>{v.title}</b><small>{v.category}</small></td><td>{v.salaryNet||'—'}</td><td>{v.quotaRemaining}</td><td><span className="status-pill">{v.isActive?'ACTIVE':'ARCHIVED'}</span></td><td><div className="row-actions"><button onClick={()=>setEditVac(v)}><Edit3 size={14}/></button><button onClick={async()=>{await vacanciesApi.archive(v.id);await load()}}><Archive size={14}/></button></div></td></tr>)}</tbody></table></div></section>}
 {section==='batch'&&<BatchView dossiers={dossiers} vacancies={vacancies} onRefresh={load}/>} 
 {section==='managers'&&<UsersView users={users} onSave={async(u)=>{await adminApi.updateUser({userId:u.id,roles:u.roles,isActive:(u as any).isActive});await load()}}/>}
 {section==='team'&&<section className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Team</h2><p>Manage public team profiles.</p></div><button className="primary-btn" onClick={()=>setTeamForm({order:team.length})}><Plus size={16}/> Add member</button></div><div className="stack-list">{team.map(m=><div className="list-row" key={m.id}><div><strong>{m.fullName}</strong><small>{m.position} · {m.languages.join(', ')}</small></div><button className="secondary-btn" onClick={()=>setTeamForm(m)}><Edit3 size={14}/></button></div>)}</div></div><div className="panel"><h2>Gallery / public media</h2><p className="muted">Add an image URL and publish it to the public gallery.</p><div className="form-grid"><input placeholder="Title" value={gallery.title} onChange={e=>setGallery({...gallery,title:e.target.value})}/><input placeholder="Image URL" value={gallery.imageUrl} onChange={e=>setGallery({...gallery,imageUrl:e.target.value})}/><input placeholder="Caption" value={gallery.caption} onChange={e=>setGallery({...gallery,caption:e.target.value})}/><button className="primary-btn" onClick={async()=>{await adminApi.saveGallery(gallery);setGallery({title:'',imageUrl:'',caption:'',order:'0'});alert('Gallery item saved.')}}><Save size={15}/> Save gallery item</button></div></div></section>}
 {section==='pricing'&&<section className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Pricing catalogue</h2><p>Server-side pricing items used when creating dossiers.</p></div></div><div className="stack-list">{pricing.map(p=><div className="list-row" key={p.id}><div><strong>{p.name} · {p.amount} {p.currency}</strong><small>{p.description}</small></div><span className="status-pill">{p.active?'ACTIVE':'OFF'}</span></div>)}</div></div><div className="panel"><h2>Add / update pricing</h2><div className="form-grid"><input placeholder="Name" value={newPricing.name||''} onChange={e=>setNewPricing({...newPricing,name:e.target.value})}/><input placeholder="Amount" type="number" value={newPricing.amount??''} onChange={e=>setNewPricing({...newPricing,amount:Number(e.target.value)})}/><input placeholder="Currency" value={newPricing.currency||'EUR'} onChange={e=>setNewPricing({...newPricing,currency:e.target.value})}/><textarea placeholder="Description" value={newPricing.description||''} onChange={e=>setNewPricing({...newPricing,description:e.target.value})}/><button className="primary-btn" onClick={async()=>{await adminApi.savePricing(newPricing);setNewPricing({currency:'EUR',active:true});await load()}}><Save size={15}/> Save pricing</button></div></div></section>}
 {section==='content'&&<section className="content-grid"><div className="panel"><h2>System / content settings</h2><p className="muted">Use keys such as hero_title, hero_subtitle, support_email, office_address or legal_notice. Values are server-stored.</p><div className="form-grid"><input placeholder="Setting key" value={setting.key} onChange={e=>setSetting({...setting,key:e.target.value})}/><textarea placeholder="Value" value={setting.value} onChange={e=>setSetting({...setting,value:e.target.value})}/><button className="primary-btn" onClick={async()=>{await adminApi.saveSetting(setting);setSetting({key:'',value:''});alert('Setting saved.')}}><Save size={15}/> Save setting</button></div></div></section>}
 {section==='audit'&&<section className="panel"><div className="panel-head"><div><h2>Audit log</h2><p>Recent critical actions.</p></div></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{new Date(x.timestamp).toLocaleString()}</td><td>{x.actorUserId}</td><td>{x.action}</td><td>{x.targetEntity} / {x.targetEntityId}</td><td>{x.details||'—'}</td></tr>)}</tbody></table></div></section>}
 {section==='backups'&&<section className="panel"><h2>Backups</h2><p className="muted">Create a JSON snapshot of all configured Sheets and store it in the Google Drive root.</p><button className="primary-btn" onClick={async()=>{const r=await adminApi.backup();alert(`Backup ${r.backup.id} created.`)}}><Database size={15}/> Create Drive backup</button></section>}
 {section==='support'&&<SupportView/>}
 </main>
 {editVac&&<Modal title={editVac.id?'Edit vacancy':'Create vacancy'} onClose={()=>setEditVac(null)}><div className="form-grid two"><input placeholder="Title" value={editVac.title||''} onChange={e=>setEditVac({...editVac,title:e.target.value})}/><input placeholder="Category" value={editVac.category||''} onChange={e=>setEditVac({...editVac,category:e.target.value})}/><input placeholder="Country" value={editVac.country||''} onChange={e=>setEditVac({...editVac,country:e.target.value})}/><input placeholder="Net salary" value={editVac.salaryNet||''} onChange={e=>setEditVac({...editVac,salaryNet:e.target.value})}/><input placeholder="Gross salary" value={editVac.salaryGross||''} onChange={e=>setEditVac({...editVac,salaryGross:e.target.value})}/><input placeholder="Working hours" value={editVac.workingHours||''} onChange={e=>setEditVac({...editVac,workingHours:e.target.value})}/><input placeholder="Accommodation" value={editVac.accommodation||''} onChange={e=>setEditVac({...editVac,accommodation:e.target.value})}/><input type="number" placeholder="Quota" value={editVac.quotaRemaining??0} onChange={e=>setEditVac({...editVac,quotaRemaining:Number(e.target.value)})}/><textarea className="wide" placeholder="Description" value={editVac.description||''} onChange={e=>setEditVac({...editVac,description:e.target.value})}/><label className="check"><input type="checkbox" checked={editVac.isActive!==false} onChange={e=>setEditVac({...editVac,isActive:e.target.checked})}/> Active vacancy</label><button className="primary-btn wide" onClick={saveVacancy}><Save size={15}/> Save vacancy</button></div></Modal>}
 {teamForm&&<Modal title={teamForm.id?'Edit team member':'Add team member'} onClose={()=>setTeamForm(null)}><div className="form-grid"><input placeholder="Full name" value={teamForm.fullName||''} onChange={e=>setTeamForm({...teamForm,fullName:e.target.value})}/><input placeholder="Position" value={teamForm.position||''} onChange={e=>setTeamForm({...teamForm,position:e.target.value})}/><input placeholder="Photo URL" value={teamForm.photoUrl||''} onChange={e=>setTeamForm({...teamForm,photoUrl:e.target.value})}/><input placeholder="Languages, comma separated" value={(teamForm.languages||[]).join(', ')} onChange={e=>setTeamForm({...teamForm,languages:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/><textarea placeholder="Bio" value={teamForm.bio||''} onChange={e=>setTeamForm({...teamForm,bio:e.target.value})}/><button className="primary-btn" onClick={saveTeam}><Save size={15}/> Save member</button></div></Modal>}
 </div>}

const Overview=({stats,apps,docs,payments,dossiers}:{stats:any;apps:Application[];docs:DossierDocument[];payments:PaymentTransaction[];dossiers:Dossier[]})=><><div className="grid-cards"><div className="stat-card"><ClipboardList/><span>Applications</span><strong>{stats.counts?.applications??apps.length}</strong></div><div className="stat-card"><FileText/><span>Dossiers</span><strong>{stats.counts?.dossiers??dossiers.length}</strong></div><div className="stat-card"><CreditCard/><span>Payments pending</span><strong>{stats.pendingPayments??payments.filter(x=>x.status==='PENDING_REVIEW').length}</strong></div><div className="stat-card"><FileText/><span>Docs pending</span><strong>{stats.pendingDocuments??docs.filter(x=>x.status==='UPLOADED').length}</strong></div></div><div className="content-grid"><section className="panel"><h2>Operational queue</h2><div className="stack-list"><div className="list-row"><span>Pending applications</span><b>{apps.filter(x=>['SUBMITTED','UNDER_REVIEW'].includes(x.status)).length}</b></div><div className="list-row"><span>Documents awaiting review</span><b>{docs.filter(x=>x.status==='UPLOADED').length}</b></div><div className="list-row"><span>Payments awaiting review</span><b>{payments.filter(x=>x.status==='PENDING_REVIEW').length}</b></div></div></section><section className="panel"><h2>Dossier pipeline</h2><div className="stack-list">{['NEW','DOCUMENTS_REQUIRED','DOCUMENTS_REVIEW','LEGAL_REVIEW','READY_FOR_FILING','FILED','PROCESSING','APPROVED','COMPLETED'].map(s=><div className="list-row" key={s}><span>{label(s)}</span><b>{dossiers.filter(d=>d.processStatus===s).length}</b></div>)}</div></section></div></>;
const ApplicationsView=({apps,vacancies,onUpdate,onCreateDossier}:{apps:Application[];vacancies:Vacancy[];onUpdate:(a:Application,s:any)=>Promise<void>;onCreateDossier:(a:Application)=>Promise<void>})=><section className="panel"><div className="panel-head"><div><h2>Application CRM</h2><p>Review applications, assign workflow status and convert accepted applications into dossiers.</p></div></div><div className="table-wrap"><table><thead><tr><th>Application</th><th>Vacancy</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td><b>{a.id}</b><small>{a.userId}</small></td><td>{vacancies.find(v=>v.id===a.vacancyId)?.title||a.vacancyId}</td><td><select value={a.status} onChange={e=>void onUpdate(a,e.target.value)}><option>SUBMITTED</option><option>UNDER_REVIEW</option><option>SHORTLISTED</option><option>ACCEPTED</option><option>REJECTED</option><option>WITHDRAWN</option></select></td><td>{new Date(a.createdAt).toLocaleDateString()}</td><td>{a.status==='ACCEPTED'&&<button className="secondary-btn" onClick={()=>void onCreateDossier(a)}>Create dossier</button>}</td></tr>)}</tbody></table></div></section>;
const DossiersView=({dossiers,onUpdate}:{dossiers:Dossier[];onUpdate:(d:Dossier,s:any)=>Promise<void>})=><section className="panel"><div className="panel-head"><div><h2>Dossier CRM</h2><p>Process status is controlled by staff.</p></div></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Client</th><th>Country</th><th>Process</th><th>Payment</th><th>Balance</th></tr></thead><tbody>{dossiers.map(d=><tr key={d.id}><td className="mono">{d.id}</td><td><b>{d.fullName}</b><small>{d.passportNumber}</small></td><td>{d.targetCountry}</td><td><select value={d.processStatus} onChange={e=>void onUpdate(d,e.target.value)}>{['NEW','DOCUMENTS_REQUIRED','DOCUMENTS_REVIEW','LEGAL_REVIEW','READY_FOR_FILING','FILED','PROCESSING','APPROVED','COMPLETED','REJECTED','ON_HOLD','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></td><td>{d.paymentStatus}</td><td>{d.remainingAmount} {d.currency}</td></tr>)}</tbody></table></div></section>;
const DocumentsView=({docs,onReview}:{docs:DossierDocument[];onReview:(id:string,s:'APPROVED'|'REJECTED')=>Promise<void>})=><section className="panel"><h2>Document review queue</h2><div className="table-wrap"><table><thead><tr><th>Document</th><th>Dossier</th><th>Category</th><th>Status</th><th>Review</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><b>{d.fileName}</b><small>{d.id}</small></td><td>{d.dossierId}</td><td>{label(d.category)}</td><td>{d.status}</td><td><div className="row-actions"><button className="ok" onClick={()=>void onReview(d.id,'APPROVED')}><Check size={14}/></button><button className="danger" onClick={()=>void onReview(d.id,'REJECTED')}><X size={14}/></button></div></td></tr>)}</tbody></table></div></section>;
const PaymentsView=({payments,onReview}:{payments:PaymentTransaction[];onReview:(id:string,s:'CONFIRMED'|'REJECTED'|'REFUNDED')=>Promise<void>})=><section className="panel"><h2>Finance / payment review</h2><div className="table-wrap"><table><thead><tr><th>ID</th><th>Dossier</th><th>Amount</th><th>Tranche</th><th>Tx hash</th><th>Status</th><th>Review</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td className="mono">{p.id}</td><td>{p.dossierId}</td><td>{p.amount} {p.currency}</td><td>{p.tranchePercent}%</td><td className="mono">{p.txHash.slice(0,20)}…</td><td>{p.status}</td><td><div className="row-actions"><button className="ok" onClick={()=>void onReview(p.id,'CONFIRMED')}><Check size={14}/></button><button className="danger" onClick={()=>void onReview(p.id,'REJECTED')}><X size={14}/></button></div></td></tr>)}</tbody></table></div></section>;
const SLAVView=({dossiers,docs,payments}:{dossiers:Dossier[];docs:DossierDocument[];payments:PaymentTransaction[]})=><section className="content-grid"><div className="panel"><h2>Legal review queue</h2><div className="stack-list">{dossiers.filter(d=>['LEGAL_REVIEW','READY_FOR_FILING','FILED'].includes(d.processStatus)).map(d=><div className="list-row" key={d.id}><div><b>{d.id}</b><small>{d.fullName} · {d.targetCountry}</small></div><span className="status-pill">{label(d.processStatus)}</span></div>)}</div></div><div className="panel"><h2>SLA indicators</h2><div className="stack-list"><div className="list-row"><span>Pending documents</span><b>{docs.filter(x=>x.status==='UPLOADED').length}</b></div><div className="list-row"><span>Pending payments</span><b>{payments.filter(x=>x.status==='PENDING_REVIEW').length}</b></div><div className="list-row"><span>On hold dossiers</span><b>{dossiers.filter(x=>x.processStatus==='ON_HOLD').length}</b></div></div></div></section>;
const BatchView=({dossiers,vacancies,onRefresh}:{dossiers:Dossier[];vacancies:Vacancy[];onRefresh:()=>Promise<void>})=><section className="content-grid"><div className="panel"><h2>Batch dossier tools</h2><p className="muted">Use this area for controlled operational batches.</p><button className="secondary-btn" onClick={()=>alert(`Current dossier count: ${dossiers.length}`)}>Generate queue report</button></div><div className="panel"><h2>Vacancy batch</h2><p className="muted">Archive inactive zero-quota vacancies.</p><button className="secondary-btn" onClick={async()=>{for(const v of vacancies.filter(x=>x.isActive&&x.quotaRemaining===0))await fetch(`/api/vacancies?id=${encodeURIComponent(v.id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${localStorage.getItem('vanguard_token')||''}`,'Content-Type':'application/json'}});await onRefresh();alert('Zero-quota vacancies archived.')}}>Archive zero-quota vacancies</button></div></section>;
const UsersView=({users,onSave}:{users:User[];onSave:(u:User&{isActive?:boolean})=>Promise<void>})=><section className="panel"><h2>Managers & users</h2><p className="muted">Two users may carry ADMIN + MANAGER simultaneously.</p><div className="table-wrap"><table><thead><tr><th>User</th><th>Roles</th><th>Active</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.fullName}</b><small>{u.email} · {u.phone}</small></td><td><select value={u.roles[0]} onChange={e=>void onSave({...u,roles:e.target.value==='ADMIN'?['ADMIN','MANAGER']:e.target.value==='MANAGER'?['MANAGER']:['CLIENT']})}><option>CLIENT</option><option>MANAGER</option><option>ADMIN</option></select></td><td>{(u as any).isActive===false?'OFF':'ON'}</td><td><button className="secondary-btn" onClick={()=>void onSave({...u,roles:u.roles,isActive:(u as any).isActive===false})}>Toggle</button></td></tr>)}</tbody></table></div></section>;
const SupportView=()=>{const [tickets,setTickets]=useState<any[]>([]);useEffect(()=>{adminApi.support().then(r=>setTickets(r.tickets)).catch(console.error)},[]);return <section className="panel"><h2>Support desk</h2><div className="stack-list">{tickets.map(t=><div className="list-row" key={t.id}><div><b>{t.subject}</b><small>{t.id} · {t.message}</small></div><span className="status-pill">{t.status}</span></div>)}</div></section>};
const Modal=({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode})=><div className="modal-backdrop"><div className="modal"><div className="panel-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose}><X size={17}/></button></div>{children}</div></div>;
