import React,{useEffect,useMemo,useState} from 'react';
import { useAuth } from '../context/AuthContext';
import { applicationsApi,adminApi,documentsApi,dossiersApi,paymentsApi,vacanciesApi } from '../services/api';
import type { Application,Dossier,DossierDocument,PaymentTransaction,Vacancy,DocumentCategory } from '../types';
import { downloadContract,downloadInvoice,downloadJobOffer } from '../utils/pdf';
import { FileText,Upload,CreditCard,Briefcase,ClipboardList,LifeBuoy,Download,Plus,RefreshCw,CheckCircle2,AlertCircle } from 'lucide-react';

const docCats:DocumentCategory[]=['PASSPORT','POLICE_CLEARANCE','EDUCATION_DIPLOMA','MEDICAL_CLEARANCE','CONTRACT'];
const label=(s:string)=>s.replace(/_/g,' ');
export const ClientPortal:React.FC<{section?:string}> = ({section='overview'})=>{
 const {user}=useAuth(); const [tab,setTab]=useState(section); const [apps,setApps]=useState<Application[]>([]); const [vacancies,setVacancies]=useState<Vacancy[]>([]); const [selected,setSelected]=useState<Dossier|null>(null); const [docs,setDocs]=useState<DossierDocument[]>([]); const [payments,setPayments]=useState<PaymentTransaction[]>([]); const [loading,setLoading]=useState(true); const [appForm,setAppForm]=useState({vacancyId:'',phone:user?.phone||'',note:''}); const [docCat,setDocCat]=useState<DocumentCategory>('PASSPORT'); const [uploading,setUploading]=useState(false); const [pay,setPay]=useState({amount:'',txHash:'',tranche:'20'}); const [ticket,setTicket]=useState({subject:'',message:''});
 const load=async()=>{setLoading(true);try{const [a,v,d]=await Promise.all([applicationsApi.list(),vacanciesApi.list(),dossiersApi.list()]);setApps(a.applications);setVacancies(v.vacancies);if(!selected&&d.dossiers[0])setSelected(d.dossiers[0]);}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]); useEffect(()=>{if(selected){Promise.all([documentsApi.list(selected.id),paymentsApi.list(selected.id)]).then(([d,p])=>{setDocs(d.documents);setPayments(p.payments)}).catch(console.error)}},[selected]);
 const activeApp=useMemo(()=>apps.find(a=>a.status==='ACCEPTED')||apps[0],[apps]); const vacancy=vacancies.find(v=>v.id===activeApp?.vacancyId);
 const apply=async(e:React.FormEvent)=>{e.preventDefault();try{await applicationsApi.create({vacancyId:appForm.vacancyId,applicantData:{fullName:user?.fullName,phone:appForm.phone,note:appForm.note}});setAppForm({...appForm,note:''});await load();setTab('applications');}catch(e){alert(e instanceof Error?e.message:'Application failed')}};
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!selected)return;setUploading(true);try{const base64=(await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)}));await documentsApi.upload({dossierId:selected.id,category:docCat,fileName:file.name,mimeType:file.type||'application/octet-stream',fileBase64:base64});const x=await documentsApi.list(selected.id);setDocs(x.documents)}catch(e){alert(e instanceof Error?e.message:'Upload failed')}finally{setUploading(false);e.target.value=''}};
 const submitPay=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;try{await paymentsApi.submit({dossierId:selected.id,amount:Number(pay.amount),currency:selected.currency,network:'TRC-20',txHash:pay.txHash,tranchePercent:Number(pay.tranche)});setPay({amount:'',txHash:'',tranche:'20'});const x=await paymentsApi.list(selected.id);setPayments(x.payments)}catch(e){alert(e instanceof Error?e.message:'Payment submission failed')}};
 const createTicket=async(e:React.FormEvent)=>{e.preventDefault();try{await adminApi.createTicket({subject:ticket.subject,message:ticket.message,dossierId:selected?.id});setTicket({subject:'',message:''});alert('Support request submitted.')}catch(e){alert(e instanceof Error?e.message:'Support request failed')}};
 if(loading)return <div className="page-wrap"><div className="skeleton-card">Loading your secure portal…</div></div>;
 return <div className="page-wrap space-y-5">
  <div className="portal-hero"><div><p className="eyebrow">CLIENT PORTAL</p><h1>Welcome, {user?.fullName}</h1><p>Applications, documents, payments and generated documents in one secure workspace.</p></div><button className="icon-btn" onClick={()=>void load()}><RefreshCw size={17}/></button></div>
  <div className="portal-tabs">{[['overview','Overview'],['applications','Applications'],['documents','Documents'],['payments','Payments'],['support','Support']].map(([id,name])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}>{name}</button>)}</div>
  {tab==='overview'&&<div className="grid-cards"><div className="stat-card"><Briefcase/><span>Applications</span><strong>{apps.length}</strong></div><div className="stat-card"><FileText/><span>Documents</span><strong>{docs.length}</strong></div><div className="stat-card"><CreditCard/><span>Outstanding</span><strong>{selected?`${selected.remainingAmount.toFixed(2)} ${selected.currency}`:'—'}</strong></div><div className="stat-card"><ClipboardList/><span>Dossier</span><strong>{selected?.id||'Not created'}</strong></div></div>}
  {tab==='applications'&&<div className="content-grid"><section className="panel"><div className="panel-head"><div><h2>My applications</h2><p>Track every submitted vacancy request.</p></div></div>{apps.length===0?<Empty text="No applications yet."/>:<div className="stack-list">{apps.map(a=><div className="list-row" key={a.id}><div><strong>{vacancies.find(v=>v.id===a.vacancyId)?.title||a.vacancyId}</strong><small>{a.id} · {new Date(a.createdAt).toLocaleString()}</small></div><Status text={a.status}/></div>)}</div>}</section><section className="panel"><div className="panel-head"><div><h2>Apply for a vacancy</h2><p>Submit your details to the selected vacancy.</p></div></div><form onSubmit={apply} className="form-grid"><select required value={appForm.vacancyId} onChange={e=>setAppForm({...appForm,vacancyId:e.target.value})}><option value="">Select country / vacancy</option>{vacancies.map(v=><option key={v.id} value={v.id}>{v.country} · {v.title} · {v.quotaRemaining} places</option>)}</select><input required value={appForm.phone} onChange={e=>setAppForm({...appForm,phone:e.target.value})} placeholder="Contact phone"/><textarea value={appForm.note} onChange={e=>setAppForm({...appForm,note:e.target.value})} placeholder="Additional information"/><button className="primary-btn" type="submit"><Plus size={16}/> Submit application</button></form></section></div>}
  {tab==='documents'&&<div className="content-grid"><section className="panel"><div className="panel-head"><div><h2>Dossier documents</h2><p>Upload files directly to the secure Google Drive vault.</p></div></div>{!selected?<Empty text="A dossier will appear here after your application is accepted and processed."/>:<><div className="inline-form"><select value={docCat} onChange={e=>setDocCat(e.target.value as DocumentCategory)}>{docCats.map(c=><option key={c}>{c}</option>)}</select><label className="upload-btn"><Upload size={16}/>{uploading?'Uploading…':'Upload document'}<input type="file" onChange={upload} disabled={uploading}/></label></div><div className="stack-list">{docs.map(d=><div className="list-row" key={d.id}><div><strong>{label(d.category)}</strong><small>{d.fileName}</small></div><Status text={d.status}/></div>)}</div></>}</section><section className="panel"><h2>Generated documents</h2><p className="muted">Generate structured drafts from your current dossier data.</p>{selected?<div className="button-stack"><button className="secondary-btn" onClick={()=>downloadContract(selected)}><Download size={15}/> Service agreement draft</button><button className="secondary-btn" onClick={()=>downloadInvoice(selected)}><Download size={15}/> Invoice / payment statement</button><button className="secondary-btn" onClick={()=>downloadJobOffer(user!,selected,vacancy)}><Download size={15}/> Job offer letter draft</button></div>:<Empty text="No dossier yet."/>}</section></div>}
  {tab==='payments'&&<div className="content-grid"><section className="panel"><h2>Payment schedule</h2><p className="muted">Payments are submitted for staff review. They are not confirmed automatically.</p>{selected&&<div className="payment-summary"><span>Total <b>{selected.totalCost} {selected.currency}</b></span><span>Paid <b>{selected.paidAmount} {selected.currency}</b></span><span>Remaining <b>{selected.remainingAmount} {selected.currency}</b></span></div>}<div className="stack-list">{payments.map(p=><div className="list-row" key={p.id}><div><strong>{p.amount} {p.currency} · {p.tranchePercent}%</strong><small>{p.txHash.slice(0,22)}…</small></div><Status text={p.status}/></div>)}</div></section><section className="panel"><h2>Submit transaction</h2>{!selected?<Empty text="No dossier available."/>:<form onSubmit={submitPay} className="form-grid"><select value={pay.tranche} onChange={e=>setPay({...pay,tranche:e.target.value})}><option value="20">20% advance</option><option value="50">50% milestone</option><option value="30">30% final</option></select><input required type="number" step="0.01" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})} placeholder={`Amount in ${selected.currency}`}/><input required value={pay.txHash} onChange={e=>setPay({...pay,txHash:e.target.value})} placeholder="Transaction hash"/><button className="primary-btn">Submit for review</button></form>}</section></div>}
  {tab==='support'&&<div className="content-grid"><section className="panel"><h2>Support desk</h2><p className="muted">Send a request to your assigned team.</p><form onSubmit={createTicket} className="form-grid"><input required value={ticket.subject} onChange={e=>setTicket({...ticket,subject:e.target.value})} placeholder="Subject"/><textarea required value={ticket.message} onChange={e=>setTicket({...ticket,message:e.target.value})} placeholder="Describe your request"/><button className="primary-btn"><LifeBuoy size={16}/> Open support ticket</button></form></section><section className="panel"><h2>Current dossier</h2>{selected?<><div className="detail-list"><span>Status <b>{label(selected.processStatus)}</b></span><span>Payment <b>{label(selected.paymentStatus)}</b></span><span>Country <b>{selected.targetCountry}</b></span><span>Manager <b>{selected.assignedManagerId||'Pending assignment'}</b></span></div></>:<Empty text="No active dossier."/>}</section></div>}
 </div>
}
const Status=({text}:{text:string})=><span className="status-pill"><CheckCircle2 size={12}/>{label(text)}</span>;const Empty=({text}:{text:string})=><div className="empty-state"><AlertCircle size={22}/><span>{text}</span></div>;
