import type { Dossier,DossierDocument,PaymentTransaction,Vacancy,TeamMember,User,Application,PricingItem,SystemSetting,GalleryItem,SupportTicket,AuditLogEntry } from '../types';
async function apiFetch(endpoint:string,options:RequestInit={}){const token=localStorage.getItem('vanguard_token');const headers:Record<string,string>={'Content-Type':'application/json',...(options.headers as Record<string,string>)};if(token)headers.Authorization=`Bearer ${token.replace(/\s/g,'')}`;const res=await fetch(`/api${endpoint}`,{...options,headers});const text=await res.text();let data:any={};try{data=JSON.parse(text)}catch{data={error:text||`HTTP ${res.status}`}}if(!res.ok)throw new Error(data.error||data.message||`Server Error (${res.status})`);return data;}
export const authApi={login:(identifier:string,password:string)=>apiFetch('/auth',{method:'POST',body:JSON.stringify({action:'login',email:identifier,phone:identifier,password})}) as Promise<{token:string;user:User}>,register:(data:{email:string;password:string;fullName:string;phone:string})=>apiFetch('/auth',{method:'POST',body:JSON.stringify({action:'register',...data})}) as Promise<{token:string;user:User}>,me:(token?:string)=>apiFetch('/auth',{headers:token?{Authorization:`Bearer ${token}`}:{}}) as Promise<{user:User}>};
export const dossiersApi={list:()=>apiFetch('/dossiers') as Promise<{dossiers:Dossier[]}>,create:(data:any)=>apiFetch('/dossiers',{method:'POST',body:JSON.stringify({action:'create',...data})}) as Promise<{dossier:Dossier}>,updateStatus:(data:any)=>apiFetch('/dossiers',{method:'POST',body:JSON.stringify({action:'updateStatus',...data})}) as Promise<{dossier:Dossier}>};
export const documentsApi={list:(dossierId:string)=>apiFetch(`/documents?dossierId=${encodeURIComponent(dossierId)}`) as Promise<{documents:DossierDocument[]}>,upload:(data:any)=>apiFetch('/documents',{method:'POST',body:JSON.stringify({action:'upload',...data})}) as Promise<{document:DossierDocument}>,review:(data:any)=>apiFetch('/documents',{method:'POST',body:JSON.stringify({action:'review',...data})}) as Promise<{document:DossierDocument}>};
export const paymentsApi={list:(dossierId?:string)=>apiFetch(dossierId?`/payments?dossierId=${encodeURIComponent(dossierId)}`:'/payments') as Promise<{payments:PaymentTransaction[]}>,submit:(data:any)=>apiFetch('/payments',{method:'POST',body:JSON.stringify({action:'submit',...data})}) as Promise<{payment:PaymentTransaction}>,review:(data:any)=>apiFetch('/payments',{method:'POST',body:JSON.stringify({action:'review',...data})}) as Promise<{payment:PaymentTransaction}>};
export const vacanciesApi={list:()=>apiFetch('/vacancies') as Promise<{vacancies:Vacancy[]}>,create:(data:any)=>apiFetch('/vacancies',{method:'POST',body:JSON.stringify({action:'create',...data})}) as Promise<{vacancy:Vacancy}>,update:(data:any)=>apiFetch('/vacancies',{method:'PATCH',body:JSON.stringify({action:'update',...data})}) as Promise<{vacancy:Vacancy}>,archive:(id:string)=>apiFetch(`/vacancies?id=${encodeURIComponent(id)}`,{method:'DELETE'}) as Promise<{vacancy:Vacancy}>};
export const applicationsApi={list:()=>apiFetch('/applications') as Promise<{applications:Application[]}>,create:(data:any)=>apiFetch('/applications',{method:'POST',body:JSON.stringify({action:'create',...data})}) as Promise<{application:Application}>,update:(data:any)=>apiFetch('/applications',{method:'POST',body:JSON.stringify({action:'update',...data})}) as Promise<{application:Application}>};
export const teamApi={list:()=>apiFetch('/team') as Promise<{team:TeamMember[]}>,create:(data:any)=>apiFetch('/team',{method:'POST',body:JSON.stringify({action:'create',...data})}) as Promise<{member:TeamMember}>,update:(data:any)=>apiFetch('/team',{method:'PATCH',body:JSON.stringify(data)}) as Promise<{member:TeamMember}>};
export const contentApi={get:()=>apiFetch('/content') as Promise<{settings:Record<string,string>;gallery:any[]}>};
export const pricingApi={list:()=>apiFetch('/pricing') as Promise<{items:PricingItem[]}>};
export const adminApi={dashboard:()=>apiFetch('/admin?action=dashboard'),users:()=>apiFetch('/admin?action=users') as Promise<{users:User[]}>,updateUser:(data:any)=>apiFetch('/admin?action=users',{method:'POST',body:JSON.stringify(data)}),audit:()=>apiFetch('/admin?action=audit') as Promise<{logs:AuditLogEntry[]}>,pricing:()=>apiFetch('/admin?action=pricing') as Promise<{items:PricingItem[]}>,savePricing:(data:any)=>apiFetch('/admin?action=pricing',{method:'POST',body:JSON.stringify(data)}),settings:()=>apiFetch('/admin?action=settings') as Promise<{settings:SystemSetting[]}>,saveSetting:(data:any)=>apiFetch('/admin?action=settings',{method:'POST',body:JSON.stringify(data)}),gallery:()=>apiFetch('/admin?action=gallery') as Promise<{items:GalleryItem[]}>,saveGallery:(data:any)=>apiFetch('/admin?action=gallery',{method:'POST',body:JSON.stringify(data)}),support:()=>apiFetch('/admin?action=support') as Promise<{tickets:SupportTicket[]}>,createTicket:(data:any)=>apiFetch('/admin?action=support',{method:'POST',body:JSON.stringify(data)}),updateTicket:(data:any)=>apiFetch('/admin?action=support',{method:'POST',body:JSON.stringify(data)}),backup:()=>apiFetch('/admin?action=backup',{method:'POST'})};
