import React,{useEffect,useState} from 'react';
import {AuthProvider,useAuth} from './context/AuthContext';
import {Navbar,AppRoute} from './components/Navbar';
import {ClientPortal} from './components/ClientPortal';
import {AdminPanel} from './components/AdminPanel';
import {ManagerDashboard} from './components/ManagerDashboard';
import {VacanciesPage,TeamPage} from './components/PublicPages';
import {ArrowRight,ShieldCheck,Globe2,LockKeyhole,ChevronRight} from 'lucide-react';
import {contentApi} from './services/api';
const Home:React.FC<{go:(r:AppRoute)=>void}>=({go})=>{const [content,setContent]=useState<{settings:Record<string,string>;gallery:any[]}>({settings:{},gallery:[]});useEffect(()=>{contentApi.get().then(setContent).catch(()=>{})},[]);const s=content.settings;return <div><section className="hero"><div className="hero-glow"/><div className="page-wrap hero-inner"><div className="hero-copy"><p className="eyebrow">{s.hero_eyebrow||'VANGUARD GLOBAL MOBILITY · SECURE OPERATIONS'}</p><h1>{s.hero_title||'European mobility, managed with precision.'}</h1><p className="hero-sub">{s.hero_subtitle||'A secure workspace for applications, employment opportunities, documents, payment review and operational case management.'}</p><div className="hero-actions"><button className="primary-btn" onClick={()=>go('vacancies')}>Explore vacancies <ArrowRight size={16}/></button><button className="secondary-btn" onClick={()=>go('portal')}>Open portal</button></div><div className="trust-row"><span><ShieldCheck/> Structured workflow</span><span><LockKeyhole/> Server-side access</span><span><Globe2/> Multi-country operations</span></div></div><div className="hero-card"><div className="hero-card-top"><span>OPERATIONS</span><span className="live-dot">LIVE</span></div><div className="hero-card-line"><b>Applications</b><span>→ review → shortlist → dossier</span></div><div className="hero-card-line"><b>Documents</b><span>→ upload → review → approve</span></div><div className="hero-card-line"><b>Payments</b><span>→ submit → staff review</span></div><div className="hero-card-footer">Google Sheets · Drive Vault · Telegram notifications</div></div></div></section><section className="page-wrap feature-section"><div className="section-hero compact"><p className="eyebrow">ONE WORKSPACE</p><h2>Everything connected to the dossier.</h2><p>Client-facing actions and staff operations are separated by server-side permissions.</p></div><div className="feature-grid">{[['Client portal','Applications, document uploads, payment submissions and generated PDF drafts.'],['Operations CRM','Dossiers, legal queue, SLA indicators, document and payment review.'],['Vacancy management','Country-specific vacancies with full edit, quota and archive controls.'],['Executive console','Users, roles, pricing, content, gallery, audit and backups.']].map(([t,d])=><div className="feature-card" key={t}><div className="feature-icon"><ChevronRight/></div><h3>{t}</h3><p>{d}</p></div>)}</div></section>{content.gallery.length>0&&<section className="page-wrap"><div className="section-hero compact"><p className="eyebrow">FIELD GALLERY</p><h2>Vanguard in focus</h2></div><div className="team-grid">{content.gallery.map((g:any)=><article className="team-card" key={g.id}><img src={g.imageUrl} alt=""/><h2>{g.title}</h2><p>{g.caption}</p></article>)}</div></section>}</div>;}
const Main:React.FC=()=>{const [route,setRoute]=useState<AppRoute>('home');const {user,loading}=useAuth();if(loading)return <div className="app-loading">Loading Vanguard…</div>;const isStaff=!!user?.roles.some(r=>r==='ADMIN'||r==='MANAGER');const isAdmin=!!user?.roles.includes('ADMIN');return <div className="app-shell"><Navbar route={route} setRoute={setRoute}/><main>{route==='home'&&<Home go={setRoute}/>} {route==='vacancies'&&<VacanciesPage onApply={()=>setRoute(user?'portal':'home')}/>} {route==='team'&&<TeamPage/>} {route==='portal'&&(user?(isStaff?<ManagerDashboard/>:<ClientPortal/>):<Home go={setRoute}/>)} {route==='admin'&&(isAdmin?<AdminPanel/>:<Home go={setRoute}/>)}</main><footer className="footer"><div><b>VANGUARD GLOBAL MOBILITY</b><span>Secure client and operations workspace</span></div><span>© 2026 Vanguard</span></footer></div>};
export const App=()=> <AuthProvider><Main/></AuthProvider>;export default App;
