import React,{createContext,useContext,useMemo,useState} from 'react';
export type Lang='EN'|'CZ'|'UR';
type Dict=Record<string,string>;
const dicts:Record<Lang,Dict>={
 EN:{home:'Home',vacancies:'Vacancies',about:'About us',portal:'Client portal',operations:'Operations',admin:'Admin',signIn:'Sign in',signOut:'Sign out',register:'Create account',heroEyebrow:'VANGUARD GLOBAL MOBILITY · SECURE OPERATIONS',heroTitle:'European mobility, managed with precision.',heroSub:'A secure workspace for applications, employment opportunities, documents, payment review and operational case management.',explore:'Explore vacancies',calculator:'Smart service calculator',citizenship:'Citizenship',destination:'Destination country',visa:'Visa / permit type',processing:'Production option',search:'Search vacancies',estimated:'Estimated service price',standard:'Standard',priority:'Priority',express:'Express',aboutTitle:'About Vanguard',team:'Our team',partners:'Partners by country',office:'Office & field gallery',legal:'Company & legal information',license:'Licence / company documents',signInTitle:'Welcome back',registerTitle:'Create your Vanguard account',emailOrPhone:'Email or phone',email:'Email address',phone:'Phone number',password:'Password',fullName:'Full name',noAccount:'New to Vanguard?',haveAccount:'Already have an account?',continue:'Continue',create:'Create account',invalid:'Please check your details.',application:'Application',documents:'Documents',payments:'Payments',status:'Status',save:'Save',cancel:'Cancel'},
 CZ:{home:'Domů',vacancies:'Volná místa',about:'O nás',portal:'Klientský portál',operations:'Operace',admin:'Administrace',signIn:'Přihlásit',signOut:'Odhlásit',register:'Vytvořit účet',heroEyebrow:'VANGUARD GLOBAL MOBILITY · BEZPEČNÉ OPERACE',heroTitle:'Evropská mobilita řízená s přesností.',heroSub:'Bezpečný pracovní prostor pro žádosti, pracovní příležitosti, dokumenty, kontrolu plateb a správu případů.',explore:'Prohlédnout pozice',calculator:'Chytrá kalkulačka služeb',citizenship:'Občanství',destination:'Cílová země',visa:'Typ víza / povolení',processing:'Rychlost zpracování',search:'Hledat pozice',estimated:'Odhad ceny služby',standard:'Standard',priority:'Priorita',express:'Expres',aboutTitle:'O společnosti Vanguard',team:'Náš tým',partners:'Partneři podle zemí',office:'Kancelář a galerie',legal:'Firemní a právní údaje',license:'Licence / firemní dokumenty',signInTitle:'Vítejte zpět',registerTitle:'Vytvořte účet Vanguard',emailOrPhone:'E-mail nebo telefon',email:'E-mail',phone:'Telefon',password:'Heslo',fullName:'Celé jméno',noAccount:'Jste u Vanguard poprvé?',haveAccount:'Už máte účet?',continue:'Pokračovat',create:'Vytvořit účet',invalid:'Zkontrolujte prosím údaje.',application:'Žádost',documents:'Dokumenty',payments:'Platby',status:'Stav',save:'Uložit',cancel:'Zrušit'},
 UR:{home:'ہوم',vacancies:'ملازمتیں',about:'ہمارے بارے میں',portal:'کلائنٹ پورٹل',operations:'آپریشنز',admin:'ایڈمن',signIn:'سائن اِن',signOut:'سائن آؤٹ',register:'اکاؤنٹ بنائیں',heroEyebrow:'VANGUARD GLOBAL MOBILITY · محفوظ آپریشنز',heroTitle:'یورپی موبیلٹی، درستگی کے ساتھ منظم۔',heroSub:'درخواستوں، ملازمتوں، دستاویزات، ادائیگیوں اور کیس مینجمنٹ کے لیے محفوظ ورک اسپیس۔',explore:'ملازمتیں دیکھیں',calculator:'اسمارٹ سروس کیلکولیٹر',citizenship:'شہریت',destination:'منزل ملک',visa:'ویزا / پرمٹ کی قسم',processing:'پروسیسنگ آپشن',search:'ملازمتیں تلاش کریں',estimated:'تخمینی سروس قیمت',standard:'معیاری',priority:'ترجیحی',express:'ایکسپریس',aboutTitle:'Vanguard کے بارے میں',team:'ہماری ٹیم',partners:'ملک کے لحاظ سے شراکت دار',office:'دفتر اور گیلری',legal:'کمپنی اور قانونی معلومات',license:'لائسنس / کمپنی دستاویزات',signInTitle:'خوش آمدید',registerTitle:'اپنا Vanguard اکاؤنٹ بنائیں',emailOrPhone:'ای میل یا فون',email:'ای میل',phone:'فون نمبر',password:'پاس ورڈ',fullName:'پورا نام',noAccount:'Vanguard پر نئے ہیں؟',haveAccount:'پہلے سے اکاؤنٹ ہے؟',continue:'جاری رکھیں',create:'اکاؤنٹ بنائیں',invalid:'براہ کرم معلومات چیک کریں۔',application:'درخواست',documents:'دستاویزات',payments:'ادائیگیاں',status:'حیثیت',save:'محفوظ کریں',cancel:'منسوخ کریں'}
};
interface Ctx{lang:Lang;setLang:(l:Lang)=>void;t:(k:string)=>string}
const LanguageContext=createContext<Ctx|null>(null);
export const LanguageProvider:React.FC<{children:React.ReactNode}>=({children})=>{const[lang,setLangState]=useState<Lang>(()=>(localStorage.getItem('vanguard_lang') as Lang)||'EN');const setLang=(l:Lang)=>{setLangState(l);localStorage.setItem('vanguard_lang',l);document.documentElement.lang=l.toLowerCase();document.documentElement.dir=l==='UR'?'rtl':'ltr'};const t=useMemo(()=>((k:string)=>dicts[lang][k]??dicts.EN[k]??k),[lang]);return <LanguageContext.Provider value={{lang,setLang,t}}>{children}</LanguageContext.Provider>};
export const useLanguage=()=>{const c=useContext(LanguageContext);if(!c)throw new Error('useLanguage must be used within LanguageProvider');return c};
