/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FilingsRouteImport } from './routes/filings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CountryCodeRouteImport } from './routes/country.$code'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as VacanciesIdRouteImport } from './routes/vacancies_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as FilesKindIdRouteImport } from './routes/files.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingsRoute = FilingsRouteImport.update({
  id: '/filings',
  path: '/filings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/country/$code',
  path: '/country/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesIdRoute = VacanciesIdRouteImport.update({
  id: '/vacancies_/$id',
  path: '/vacancies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesKindIdRoute = FilesKindIdRouteImport.update({
  id: '/files/$kind/$id',
  path: '/files/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/filings': typeof FilingsRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/portal': typeof PortalRoute
  '/process': typeof ProcessRoute
  '/questions': typeof QuestionsRoute
  '/search': typeof SearchRoute
  '/country/$code': typeof CountryCodeRoute
  '/r/$code': typeof RCodeRoute
  '/vacancies/$id': typeof VacanciesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/files/$kind/$id': typeof FilesKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/filings': typeof FilingsRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/portal': typeof PortalRoute
  '/process': typeof ProcessRoute
  '/questions': typeof QuestionsRoute
  '/search': typeof SearchRoute
  '/country/$code': typeof CountryCodeRoute
  '/r/$code': typeof RCodeRoute
  '/vacancies/$id': typeof VacanciesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/files/$kind/$id': typeof FilesKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/filings': typeof FilingsRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/portal': typeof PortalRoute
  '/process': typeof ProcessRoute
  '/questions': typeof QuestionsRoute
  '/search': typeof SearchRoute
  '/country/$code': typeof CountryCodeRoute
  '/r/$code': typeof RCodeRoute
  '/vacancies_/$id': typeof VacanciesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/files/$kind/$id': typeof FilesKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/contact'
    | '/filings'
    | '/login'
    | '/papers'
    | '/portal'
    | '/process'
    | '/questions'
    | '/search'
    | '/country/$code'
    | '/r/$code'
    | '/vacancies/$id'
    | '/api/auth/$'
    | '/files/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/contact'
    | '/filings'
    | '/login'
    | '/papers'
    | '/portal'
    | '/process'
    | '/questions'
    | '/search'
    | '/country/$code'
    | '/r/$code'
    | '/vacancies/$id'
    | '/api/auth/$'
    | '/files/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/contact'
    | '/filings'
    | '/login'
    | '/papers'
    | '/portal'
    | '/process'
    | '/questions'
    | '/search'
    | '/country/$code'
    | '/r/$code'
    | '/vacancies_/$id'
    | '/api/auth/$'
    | '/files/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  ContactRoute: typeof ContactRoute
  FilingsRoute: typeof FilingsRoute
  LoginRoute: typeof LoginRoute
  PapersRoute: typeof PapersRoute
  PortalRoute: typeof PortalRoute
  ProcessRoute: typeof ProcessRoute
  QuestionsRoute: typeof QuestionsRoute
  SearchRoute: typeof SearchRoute
  CountryCodeRoute: typeof CountryCodeRoute
  RCodeRoute: typeof RCodeRoute
  VacanciesIdRoute: typeof VacanciesIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  FilesKindIdRoute: typeof FilesKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filings': {
      id: '/filings'
      path: '/filings'
      fullPath: '/filings'
      preLoaderRoute: typeof FilingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$code': {
      id: '/country/$code'
      path: '/country/$code'
      fullPath: '/country/$code'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies_/$id': {
      id: '/vacancies_/$id'
      path: '/vacancies/$id'
      fullPath: '/vacancies/$id'
      preLoaderRoute: typeof VacanciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$kind/$id': {
      id: '/files/$kind/$id'
      path: '/files/$kind/$id'
      fullPath: '/files/$kind/$id'
      preLoaderRoute: typeof FilesKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  ContactRoute: ContactRoute,
  FilingsRoute: FilingsRoute,
  LoginRoute: LoginRoute,
  PapersRoute: PapersRoute,
  PortalRoute: PortalRoute,
  ProcessRoute: ProcessRoute,
  QuestionsRoute: QuestionsRoute,
  SearchRoute: SearchRoute,
  CountryCodeRoute: CountryCodeRoute,
  RCodeRoute: RCodeRoute,
  VacanciesIdRoute: VacanciesIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  FilesKindIdRoute: FilesKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
