import type {Application,AuditLogEntry,BackupRecord,Dossier,DossierDocument,GalleryItem,PaymentTransaction,PricingItem,SupportTicket,SystemSetting,TeamMember,User,UserRecord,Vacancy} from '../../src/types.js';
import type {SheetRow} from './sheets.js';

const s=(v:unknown)=>String(v??'');
const n=(v:unknown,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d;};
const b=(v:unknown)=>v===true||v==='true'||v==='TRUE'||v===1||v==='1';
const j=<T>(v:unknown,d:T):T=>{if(v===undefined||v===null||v==='')return d;try{return JSON.parse(String(v)) as T}catch{return d;}};
const cleanOpt=(v:string)=>v||undefined;

export const mapRowToUser=(r:SheetRow):User=>({id:s(r.id),email:s(r.email),phone:s(r.phone),fullName:s(r.fullName),roles:j<User['roles']>(r.roles,['CLIENT']),createdAt:s(r.createdAt),lastLoginAt:cleanOpt(r.lastLoginAt)});
export const mapRowToUserRecord=(r:SheetRow):UserRecord=>({...mapRowToUser(r),passwordHash:s(r.passwordHash),isActive:b(r.isActive)});
export const mapUserToRow=(u:UserRecord):SheetRow=>({id:u.id,email:u.email,phone:u.phone,fullName:u.fullName,roles:JSON.stringify(u.roles),passwordHash:u.passwordHash,createdAt:u.createdAt,lastLoginAt:u.lastLoginAt||'',isActive:String(u.isActive)});

export const mapRowToApplication=(r:SheetRow):Application=>({id:s(r.id),userId:s(r.userId),vacancyId:s(r.vacancyId),applicantData:s(r.applicantData),status:(s(r.status)||'SUBMITTED') as Application['status'],stage:n(r.stage,1) as Application['stage'],visaProductId:cleanOpt(r.visaProductId),country:cleanOpt(r.country),processingOption:cleanOpt(r.processingOption) as Application['processingOption'],totalCost:n(r.totalCost),currency:s(r.currency)||'EUR',processStage:cleanOpt(r.processStage) as Application['processStage'],paymentDeadlineAt:cleanOpt(r.paymentDeadlineAt),documentDeadlineAt:cleanOpt(r.documentDeadlineAt),assignedManagerId:cleanOpt(r.assignedManagerId),createdAt:s(r.createdAt),updatedAt:s(r.updatedAt),approvedAt:cleanOpt(r.approvedAt),rejectedReason:cleanOpt(r.rejectedReason)});
export const mapApplicationToRow=(a:Application):SheetRow=>({id:a.id,userId:a.userId,vacancyId:a.vacancyId,applicantData:a.applicantData,status:a.status,stage:String(a.stage),visaProductId:a.visaProductId||'',country:a.country||'',processingOption:a.processingOption||'',totalCost:String(a.totalCost),currency:a.currency,processStage:a.processStage||'',paymentDeadlineAt:a.paymentDeadlineAt||'',documentDeadlineAt:a.documentDeadlineAt||'',assignedManagerId:a.assignedManagerId||'',createdAt:a.createdAt,updatedAt:a.updatedAt,approvedAt:a.approvedAt||'',rejectedReason:a.rejectedReason||''});

export const mapRowToVacancy=(r:SheetRow):Vacancy=>({id:s(r.id),title:s(r.title),category:s(r.category),country:s(r.country),salaryNet:s(r.salaryNet),salaryGross:s(r.salaryGross),accommodation:s(r.accommodation),workingHours:s(r.workingHours),description:s(r.description),quotaRemaining:n(r.quotaRemaining),isActive:b(r.isActive),visaProductId:cleanOpt(r.visaProductId),visaDuration:cleanOpt(r.visaDuration),processingOptions:j<Vacancy['processingOptions']>(r.processingOptions,undefined),employerLabel:cleanOpt(r.employerLabel),requirements:cleanOpt(r.requirements),createdAt:cleanOpt(r.createdAt),updatedAt:cleanOpt(r.updatedAt)});
export const mapVacancyToRow=(v:Vacancy):SheetRow=>({id:v.id,title:v.title,category:v.category,country:v.country,salaryNet:v.salaryNet,salaryGross:v.salaryGross,accommodation:v.accommodation,workingHours:v.workingHours,description:v.description,quotaRemaining:String(v.quotaRemaining),isActive:String(v.isActive),visaProductId:v.visaProductId||'',visaDuration:v.visaDuration||'',processingOptions:JSON.stringify(v.processingOptions||[]),employerLabel:v.employerLabel||'',requirements:v.requirements||'',createdAt:v.createdAt||'',updatedAt:v.updatedAt||''});

export const mapRowToDossier=(r:SheetRow):Dossier=>({id:s(r.id),userId:s(r.userId),fullName:s(r.fullName),passportNumber:s(r.passportNumber),citizenship:s(r.citizenship),targetCountry:s(r.targetCountry),vacancyId:cleanOpt(r.vacancyId),vacancyTitle:cleanOpt(r.vacancyTitle),processStatus:(s(r.processStatus)||'NEW') as Dossier['processStatus'],paymentStatus:(s(r.paymentStatus)||'NOT_DUE') as Dossier['paymentStatus'],currency:s(r.currency)||'EUR',totalCost:n(r.totalCost),paidAmount:n(r.paidAmount),remainingAmount:n(r.remainingAmount),assignedManagerId:cleanOpt(r.assignedManagerId),createdAt:s(r.createdAt),updatedAt:s(r.updatedAt)});
export const mapDossierToRow=(d:Dossier):SheetRow=>({id:d.id,userId:d.userId,fullName:d.fullName,passportNumber:d.passportNumber,citizenship:d.citizenship,targetCountry:d.targetCountry,vacancyId:d.vacancyId||'',vacancyTitle:d.vacancyTitle||'',processStatus:d.processStatus,paymentStatus:d.paymentStatus,currency:d.currency,totalCost:String(d.totalCost),paidAmount:String(d.paidAmount),remainingAmount:String(d.remainingAmount),assignedManagerId:d.assignedManagerId||'',createdAt:d.createdAt,updatedAt:d.updatedAt});

export const mapRowToDocument=(r:SheetRow):DossierDocument=>({id:s(r.id),dossierId:s(r.dossierId),category:s(r.category) as DossierDocument['category'],fileName:s(r.fileName),driveFileId:cleanOpt(r.driveFileId),status:(s(r.status)||'UPLOADED') as DossierDocument['status'],uploadedAt:s(r.uploadedAt),reviewedAt:cleanOpt(r.reviewedAt),reviewedBy:cleanOpt(r.reviewedBy),rejectionReason:cleanOpt(r.rejectionReason)});
export const mapDocumentToRow=(d:DossierDocument):SheetRow=>({id:d.id,dossierId:d.dossierId,category:d.category,fileName:d.fileName,driveFileId:d.driveFileId||'',status:d.status,uploadedAt:d.uploadedAt,reviewedAt:d.reviewedAt||'',reviewedBy:d.reviewedBy||'',rejectionReason:d.rejectionReason||''});

export const mapRowToPayment=(r:SheetRow):PaymentTransaction=>({id:s(r.id),dossierId:s(r.dossierId),userId:s(r.userId),amount:n(r.amount),currency:s(r.currency),network:s(r.network),txHash:s(r.txHash),tranchePercent:n(r.tranchePercent,30) as 30|40,trancheKey:cleanOpt(r.trancheKey) as PaymentTransaction['trancheKey'],status:(s(r.status)||'PENDING_REVIEW') as PaymentTransaction['status'],submittedAt:s(r.submittedAt),verifiedAt:cleanOpt(r.verifiedAt),verifiedBy:cleanOpt(r.verifiedBy),proofFileId:cleanOpt(r.proofFileId),proofFileName:cleanOpt(r.proofFileName)});
export const mapPaymentToRow=(p:PaymentTransaction):SheetRow=>({id:p.id,dossierId:p.dossierId,userId:p.userId,amount:String(p.amount),currency:p.currency,network:p.network,txHash:p.txHash,tranchePercent:String(p.tranchePercent),trancheKey:p.trancheKey||'',status:p.status,submittedAt:p.submittedAt,verifiedAt:p.verifiedAt||'',verifiedBy:p.verifiedBy||'',proofFileId:p.proofFileId||'',proofFileName:p.proofFileName||''});

export const mapRowToTeamMember=(r:SheetRow):TeamMember=>({id:s(r.id),fullName:s(r.fullName),position:s(r.position),photoUrl:s(r.photoUrl),contactPhone:cleanOpt(r.contactPhone),languages:j<string[]>(r.languages,[]),bio:s(r.bio),order:n(r.order),isActive:r.isActive===''?true:b(r.isActive)});
export const mapTeamMemberToRow=(m:TeamMember):SheetRow=>({id:m.id,fullName:m.fullName,position:m.position,photoUrl:m.photoUrl,contactPhone:m.contactPhone||'',languages:JSON.stringify(m.languages),bio:m.bio,order:String(m.order),isActive:String(m.isActive!==false)});

export const mapRowToAuditLog=(r:SheetRow):AuditLogEntry=>({id:s(r.id),actorUserId:s(r.actorUserId),action:s(r.action),targetEntity:s(r.targetEntity),targetEntityId:s(r.targetEntityId),details:cleanOpt(r.details),timestamp:s(r.timestamp)});
export const mapAuditLogToRow=(x:AuditLogEntry):SheetRow=>({id:x.id,actorUserId:x.actorUserId,action:x.action,targetEntity:x.targetEntity,targetEntityId:x.targetEntityId,details:x.details||'',timestamp:x.timestamp});
export const mapRowToPricing=(r:SheetRow):PricingItem=>({id:s(r.id),name:s(r.name),description:s(r.description),amount:n(r.amount),currency:s(r.currency)||'EUR',active:b(r.active),updatedAt:s(r.updatedAt),updatedBy:s(r.updatedBy)});
export const mapPricingToRow=(x:PricingItem):SheetRow=>({id:x.id,name:x.name,description:x.description,amount:String(x.amount),currency:x.currency,active:String(x.active),updatedAt:x.updatedAt,updatedBy:x.updatedBy});
export const mapRowToSetting=(r:SheetRow):SystemSetting=>({id:s(r.id),key:s(r.key),value:s(r.value),updatedAt:s(r.updatedAt),updatedBy:s(r.updatedBy)});
export const mapSettingToRow=(x:SystemSetting):SheetRow=>({id:x.id,key:x.key,value:x.value,updatedAt:x.updatedAt,updatedBy:x.updatedBy});
export const mapRowToGallery=(r:SheetRow):GalleryItem=>({id:s(r.id),title:s(r.title),imageUrl:s(r.imageUrl),caption:s(r.caption),order:n(r.order),isActive:b(r.isActive)});
export const mapGalleryToRow=(x:GalleryItem):SheetRow=>({id:x.id,title:x.title,imageUrl:x.imageUrl,caption:x.caption,order:String(x.order),isActive:String(x.isActive)});
export const mapRowToSupportTicket=(r:SheetRow):SupportTicket=>({id:s(r.id),userId:s(r.userId),dossierId:cleanOpt(r.dossierId),subject:s(r.subject),message:s(r.message),status:(s(r.status)||'OPEN') as SupportTicket['status'],assignedManagerId:cleanOpt(r.assignedManagerId),createdAt:s(r.createdAt),updatedAt:s(r.updatedAt)});
export const mapSupportTicketToRow=(x:SupportTicket):SheetRow=>({id:x.id,userId:x.userId,dossierId:x.dossierId||'',subject:x.subject,message:x.message,status:x.status,assignedManagerId:x.assignedManagerId||'',createdAt:x.createdAt,updatedAt:x.updatedAt});
export const mapBackupToRow=(x:BackupRecord):SheetRow=>({id:x.id,createdBy:x.createdBy,driveFileId:x.driveFileId,fileName:x.fileName,createdAt:x.createdAt});
