import crypto from 'crypto';import type {VercelRequest,VercelResponse} from '@vercel/node';import {readSheetRows,appendSheetRow,updateSheetRowById,findSheetRowById} from '../server/utils/sheets.js';import {mapRowToSetting,mapSettingToRow,mapRowToGallery,mapGalleryToRow} from '../server/utils/mappers.js';import {authenticateRequest,hasRole} from '../server/utils/permissions.js';import {uploadFileToDrive,findOrCreateFolder,makeFilePublic,deleteFileFromDrive} from '../server/utils/drive.js';
const clean=(v:unknown)=>String(v??'').trim();const admin=(req:VercelRequest,res:VercelResponse)=>{const a=authenticateRequest(req.headers.authorization);if(!a.authorized||!a.session){res.status(a.statusCode).json({error:a.errorMessage});return null}if(!hasRole(a.session,['ADMIN'])){res.status(403).json({error:'Admin role required.'});return null}return a.session};
export default async function handler(req:VercelRequest,res:VercelResponse){try{if(req.method==='GET'){const settings=(await readSheetRows('SystemSettings')).map(mapRowToSetting);const gallery=(await readSheetRows('Gallery')).map(mapRowToGallery).filter(x=>x.isActive).sort((a,b)=>a.order-b.order);return res.status(200).json({settings:Object.fromEntries(settings.map(x=>[x.key,x.value])),gallery})}const session=admin(req,res);if(!session)return;const action=clean(req.query.action||req.body?.action).toLowerCase();
if(req.method==='POST'&&action==='settings'){const key=clean(req.body?.key),value=clean(req.body?.value);if(!key)return res.status(400).json({error:'key required'});const old=(await readSheetRows('SystemSettings')).map(mapRowToSetting).find(x=>x.key===key);const item={id:old?.id||`SET-${Date.now()}`,key,value,updatedAt:new Date().toISOString(),updatedBy:session.userId};if(old)await updateSheetRowById('SystemSettings',old.id,mapSettingToRow(item));else await appendSheetRow('SystemSettings',mapSettingToRow(item));return res.status(200).json({setting:item})}
if(req.method==='POST'&&action==='uploadmedia'){const b=req.body||{},base64=clean(b.fileBase64);if(!base64)return res.status(400).json({error:'fileBase64 required'});const root=clean(process.env.GOOGLE_DRIVE_ROOT_FOLDER_ID);if(!root)return res.status(500).json({error:'GOOGLE_DRIVE_ROOT_FOLDER_ID missing'});const folder=await findOrCreateFolder(root,'Public Media');const upload=await uploadFileToDrive(folder,clean(b.fileName)||`media-${crypto.randomInt(1000,9999)}`,clean(b.mimeType)||'application/octet-stream',Buffer.from(base64,'base64'));await makeFilePublic(upload.fileId);const publicUrl=`https://drive.google.com/uc?export=view&id=${encodeURIComponent(upload.fileId)}`;const key=clean(b.settingKey);if(key){const old=(await readSheetRows('SystemSettings')).map(mapRowToSetting).find(x=>x.key===key);const item={id:old?.id||`SET-${Date.now()}`,key,value:publicUrl,updatedAt:new Date().toISOString(),updatedBy:session.userId};if(old)await updateSheetRowById('SystemSettings',old.id,mapSettingToRow(item));else await appendSheetRow('SystemSettings',mapSettingToRow(item))}return res.status(201).json({fileId:upload.fileId,url:publicUrl})}
if(req.method==='POST'&&action==='gallery'){const b=req.body||{},id=clean(b.id);const item={id:id||`GAL-${Date.now()}`,title:clean(b.title),imageUrl:clean(b.imageUrl),caption:clean(b.caption),order:Number(b.order)||0,isActive:b.isActive===undefined?true:Boolean(b.isActive)};if(!item.title||!item.imageUrl)return res.status(400).json({error:'Gallery title and image URL are required.'});if(id&&await findSheetRowById('Gallery',id))await updateSheetRowById('Gallery',id,mapGalleryToRow(item));else await appendSheetRow('Gallery',mapGalleryToRow(item));return res.status(200).json({item})}
if(req.method==='DELETE'&&action==='gallery'){const id=clean(req.query.id||req.body?.id);const row=await findSheetRowById('Gallery',id);if(!row)return res.status(404).json({error:'Gallery item not found.'});const old=mapRowToGallery(row);await updateSheetRowById('Gallery',id,mapGalleryToRow({...old,isActive:false}));return res.status(200).json({item:{...old,isActive:false}})}
if(req.method==='DELETE'&&action==='license'){const rows=(await readSheetRows('SystemSettings')).map(mapRowToSetting);const old=rows.find(x=>x.key==='license_image_url');if(old){const value=old.value;const match=value.match(/[?&]id=([^&]+)/);if(match)await deleteFileFromDrive(decodeURIComponent(match[1])).catch(()=>{});await updateSheetRowById('SystemSettings',old.id,mapSettingToRow({...old,value:'',updatedAt:new Date().toISOString(),updatedBy:session.userId}))}return res.status(200).json({ok:true})}
return res.status(405).json({error:'Method not allowed.'});}catch(e){return res.status(500).json({error:e instanceof Error?e.message:'Internal Server Error'})}}
