import crypto from 'crypto';
import type {VercelRequest,VercelResponse} from '@vercel/node';
import type {PaymentTransaction,Dossier,DossierPaymentStatus} from '../src/types.js';
import {mapRowToPayment,mapPaymentToRow,mapRowToDossier,mapDossierToRow} from '../server/utils/mappers.js';
import {readSheetRows,findSheetRowById,appendSheetRow,updateSheetRowById} from '../server/utils/sheets.js';
import {authenticateRequest,validateOwnership,isStaff} from '../server/utils/permissions.js';
import {recordSafeAuditLog} from '../server/utils/audit.js';
import {getDossierCategoryFolder,uploadFileToDrive} from '../server/utils/drive.js';
const P='PaymentTransactions',D='Dossiers';
function auth(req:VercelRequest,res:VercelResponse){const a=authenticateRequest(req.headers.authorization);if(!a.authorized||!a.session){res.status(a.statusCode).json({error:a.errorMessage});return null}return a.session}
function recalc(d:Dossier,rows:PaymentTransaction[]):DossierPaymentStatus{const paid=Math.round(rows.filter(p=>p.dossierId===d.id&&p.status==='CONFIRMED').reduce((s,p)=>s+p.amount,0)*100)/100;return paid<=0?'NOT_DUE':paid+0.01>=d.totalCost?'PAID':'PARTIALLY_PAID'}
export default async function handler(req:VercelRequest,res:VercelResponse){try{const session=auth(req,res);if(!session)return;const action=String(req.query.action||req.body?.action||'').trim().toLowerCase();const rows=(await readSheetRows(P)).map(mapRowToPayment);
 if(req.method==='GET'){const dossierId=String(req.query.dossierId||'').trim();if(dossierId){const dr=await findSheetRowById(D,dossierId);if(!dr)return res.status(404).json({error:'Dossier not found.'});const d=mapRowToDossier(dr);const own=validateOwnership(session,d.userId);if(!own.authorized)return res.status(own.statusCode).json({error:own.errorMessage});return res.status(200).json({payments:rows.filter(x=>x.dossierId===dossierId)})}if(!isStaff(session))return res.status(403).json({error:'dossierId is required.'});return res.status(200).json({payments:rows})}
 if(req.method==='POST'&&(!action||action==='submit')){const dossierId=String(req.body?.dossierId||'').trim(),amount=Number(req.body?.amount),currency=String(req.body?.currency||'').trim().toUpperCase(),network=String(req.body?.network||'').trim().toUpperCase(),txHash=String(req.body?.txHash||'').trim(),tranche=Number(req.body?.tranchePercent) as 30|40;const dr=await findSheetRowById(D,dossierId);if(!dr)return res.status(404).json({error:'Dossier not found.'});const d=mapRowToDossier(dr);const own=validateOwnership(session,d.userId);if(!own.authorized)return res.status(own.statusCode).json({error:own.errorMessage});if(![30,40].includes(tranche))return res.status(400).json({error:'Allowed payment stages are 30% and 40%; final 30% is released in stage 4.'});if(currency!==d.currency)return res.status(400).json({error:`Currency must be ${d.currency}.`});if(!Number.isFinite(amount)||amount<=0||txHash.length<12)return res.status(400).json({error:'Valid amount and transaction hash are required.'});if(rows.some(x=>x.txHash.toLowerCase()===txHash.toLowerCase()))return res.status(409).json({error:'This transaction hash is already submitted.'});const confirmed=rows.filter(x=>x.dossierId===d.id&&x.status==='CONFIRMED');const target=tranche===30?d.totalCost*.3:d.totalCost*.4;const already=confirmed.some(x=>x.tranchePercent===tranche);if(already)return res.status(409).json({error:`The ${tranche}% invoice has already been submitted/confirmed.`});if(Math.abs(amount-Math.round(target*100)/100)>0.01)return res.status(400).json({error:`Expected ${target.toFixed(2)} ${d.currency} for ${tranche}%.`});let proofFileId='',proofFileName='';if(req.body?.proofBase64){const folder=await getDossierCategoryFolder(dossierId,'PAYMENT_PROOFS');const up=await uploadFileToDrive(folder,String(req.body.proofFileName||'payment-proof'),String(req.body.proofMimeType||'application/octet-stream'),Buffer.from(String(req.body.proofBase64),'base64'));proofFileId=up.fileId;proofFileName=String(req.body.proofFileName||'payment-proof')}const payment:PaymentTransaction={id:`PAY-${new Date().getUTCFullYear()}-${crypto.randomInt(100000,1000000)}`,dossierId,userId:session.userId,amount,currency,network,txHash,tranchePercent:tranche,status:'PENDING_REVIEW',submittedAt:new Date().toISOString(),proofFileId:proofFileId||undefined,proofFileName:proofFileName||undefined};await appendSheetRow(P,mapPaymentToRow(payment));await recordSafeAuditLog({actorUserId:session.userId,action:'PAYMENT_SUBMIT',targetEntity:'PAYMENT',targetEntityId:payment.id,details:`${tranche}%`});return res.status(201).json({payment})}
 if(req.method==='POST'&&action==='review'){if(!isStaff(session))return res.status(403).json({error:'Only staff can review payments.'});const id=String(req.body?.paymentId||'').trim(),status=String(req.body?.status||'').toUpperCase();const row=await findSheetRowById(P,id);if(!row)return res.status(404).json({error:'Payment not found.'});if(!['CONFIRMED','REJECTED','REFUNDED'].includes(status))return res.status(400).json({error:'Invalid review status.'});const old=mapRowToPayment(row);const updated={...old,status:status as any,verifiedAt:new Date().toISOString(),verifiedBy:session.userId};await updateSheetRowById(P,id,mapPaymentToRow(updated));const dr=await findSheetRowById(D,old.dossierId);if(dr){const d=mapRowToDossier(dr);const all=(await readSheetRows(P)).map(mapRowToPayment).map(x=>x.id===id?updated:x);const paid=all.filter(x=>x.dossierId===d.id&&x.status==='CONFIRMED').reduce((s,x)=>s+x.amount,0);await updateSheetRowById(D,d.id,mapDossierToRow({...d,paidAmount:Math.round(paid*100)/100,remainingAmount:Math.max(0,Math.round((d.totalCost-paid)*100)/100),paymentStatus:recalc(d,all),updatedAt:new Date().toISOString()}))}await recordSafeAuditLog({actorUserId:session.userId,action:'PAYMENT_REVIEW',targetEntity:'PAYMENT',targetEntityId:id,details:`${status}`});return res.status(200).json({payment:updated})}
 return res.status(405).json({error:'Method not allowed.'});
}catch(e){return res.status(500).json({error:e instanceof Error?e.message:'Internal Server Error'})}}
